name: Connected Tests

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Pull docker
              run: docker pull nextcloudci/android-android-54

            - name: Run
              run: docker run nextcloudci/android

            - name: start Emulator
              run: emulator-headless -avd android-27 -no-snapshot -gpu swiftshader_indirect -no-window -no-audio -skin 500x833 &

            - name: test
              run: ./gradlew assembleGplay
                  ./gradlew assembleGplayDebug
                  scripts/wait_for_emulator.sh
                  ./gradlew jacocoTestGplayDebugUnitTestReport
