name: 'Close stale issues'
on:
    schedule:
        -   cron: '*/2 * * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/stale@v3
                with:
                    days-before-stale: 0
                    days-before-close: 0
                    operations-per-run: 10
                    only-labels: 'bug, needs info/discussion'
                    stale-issue-message: 'This bug report did not receive an update in the last 4 weeks.
                                        Please take a look again and update the issue with new details,
                                        otherwise the issue will be automatically closed in 2 weeks. Thank you!'
                    exempt-all-pr-milestones: true
