name: test

on: [push]

jobs:
    container:
        runs-on: ubuntu-latest
        container: nextcloudci/android:android-49
        steps:
            - run: |
                  echo This job does specify a container.
                  echo It runs in the container instead of the VM.
              name: Run in container
